version: "3.8"

services:
  ai-api-app:
    build: .
    image: "ai-api-app"
    container_name: ai-api-app
    command:
      ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    volumes:
      - .:/code
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai-network
    restart: unless-stopped
    environment:
      USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"

networks:
  ai-network:
    name: "ai-network"
    driver: bridge
    external: true