services:
  ollama:
    build: .
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ./ollama-models:/root/.ollama
    ports:
      - 11434:11434
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai-network


  jupyter:
    build: ./jupyter
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    restart: unless-stopped
    environment:
      - JUPYTER_TOKEN=123456  # ตั้งค่า Token สำหรับการเข้าถึง
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai-network

networks:
  ai-network:
    name: "ai-network"
    driver: bridge
    external: true