services:
  ollama:
    build: .
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ./ollama-models:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # ใช้ GPU ทั้งหมดที่มี
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_USE_CUDA=1  # บอก Ollama ให้ใช้ CUDA

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - open-webui-data:/app/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434  # เชื่อมต่อ Ollama ผ่านชื่อ container
      - PORT=3000
    networks:
      - ai-network

networks:
  ai-network:
    name: "ai-network"
    driver: bridge
    external: true

volumes:
  open-webui-data:
