version: '3.8'

services:
  ai-reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-reverse-proxy
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
